.\" Manpage for gred
.TH man 1 "04 September 2023" "1.0" "gred man page"
.SH NAME
gred \- edit a text file
.SH SYNOPSIS
gred [filename]
.SH DESCRIPTION
Gred is a small, hackable, vim-like text editor.
.br
Configuration of gred is done by editing the source.
.br
The source code for gred is available at:
.br
    https://github.com/C-Caveman/gred
    
.br
Further documentation can be found in the documentation folder
.br
on the github page.
.br
 
Within gred, you can view a tutorial by pressing <?>
.SH OPTIONS
Gred does not have any cli options yet.
.SH SEE ALSO
vi(1) nano(1)
.SH BUGS
Unicode characters can displace the cursor.
.SH AUTHOR
Leo Brown
